version: 2.1

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:17.2.0

    steps:
      - run: git clone https://github.com/logpome/Labo2-Backend.git

      - run: cd Labo2-Backend && npm install

      - run: cd Labo2-Backend && npm run test

  integrationFrontend:
    docker:
      - image: cimg/node:17.2.0

    steps:
      - run: git clone https://github.com/logpome/Labo2-Backend.git

      - run: git clone https://github.com/logpome/Labo2-Frontend.git

      - run: cd Labo2-Frontend && npm install
      
      - run: cd Labo2-Frontend && npm run build

      - run: cp -rT Labo2-Frontend/build/* Labo2-Backend/public

      

workflows:
  Labo2-workflow:
    jobs:
      - checkoutEtTests
